apiVersion: v1
kind: Pod
metadata:
  name: complainer
  namespace: seccomp-test
  annotations:
    description: >-
      Test pod to exercise seccomp complain mode
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/seccomp-test/complainer.json
  containers:
    - name: complainer-container
      image: nginx

