apiVersion: v1
kind: Pod
metadata:
  name: nginx-deny
  namespace: seccomp-test
  annotations:
    description: >-
      Test pod to deny syscalls with explicit deny profile.
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/seccomp-test/confine-nginx-explicit-deny.json
  containers:
    - name: default-container
      image: nginx


