apiVersion: v1
kind: Pod
metadata:
  name: block-all
  namespace: seccomp-test
  annotations:
    description: >-
      Test pod to block all syscalls.
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/seccomp-test/profile-block-all.json
  containers:
    - name: block-all-container
      image: nginx

