apiVersion: v1
kind: Pod
metadata:
  name: nginx-allow
  namespace: seccomp-test
  annotations:
    description: >-
      Test pod to allow syscalls with explicit allow profile.
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: operator/seccomp-test/confine-nginx-explicit-allow.json
  containers:
    - name: default-container
      image: nginx


